from fastapi import APIRouter
from typing import List, Dict, Any
from app.services.data_loader import data_loader

router = APIRouter(prefix="/alerts", tags=["Early-Warning Alerts"])

@router.get("")
def get_active_alerts() -> Dict[str, Any]:
    """
    Generate real-time AI-assisted prototype alerts for severe conditions:
    Rapid Intensification, Major Hurricanes (Cat 3+), Expansive R35 footprint, and Deep Central Pressure.
    """
    summary = data_loader.get_cyclones_summary(limit=100)
    cyclones = summary.get("cyclones", [])

    alerts: List[Dict[str, Any]] = []

    for cyc in cyclones:
        cid = cyc["cyclone_id"]
        basin = cyc["basin"]
        vmax = cyc["current_vmax"]
        peak_vmax = cyc["peak_vmax"]
        r35 = cyc["current_r35"]
        mslp = cyc["current_mslp"]
        time_str = cyc["end_time"]
        is_ri = cyc["is_ri"]
        trend = cyc["trend"]

        # 1. Rapid Intensification Alert
        if is_ri or "RAPID" in trend:
            alerts.append({
                "alert_id": f"RI-{cid}",
                "type": "RAPID_INTENSIFICATION",
                "severity": "CRITICAL",
                "title": "RAPID INTENSIFICATION DETECTED",
                "cyclone_id": cid,
                "basin": basin,
                "timestamp": time_str,
                "current_vmax": vmax,
                "reason": "Vmax increased significantly over the recent observation window (ΔVmax ≥ 10 kt / 6h).",
                "recommendation": "Initiate immediate high-frequency satellite surveillance and review convective eyewall symmetry.",
                "badge": "[AI-ASSISTED PROTOTYPE ALERT]"
            })

        # 2. Major Cyclone (Category 3, 4, 5) Alert
        if vmax >= 96.0:
            cat = "Category 5" if vmax >= 137 else ("Category 4" if vmax >= 113 else "Category 3")
            alerts.append({
                "alert_id": f"MAJOR-{cid}",
                "type": "MAJOR_CYCLONE",
                "severity": "HIGH",
                "title": f"MAJOR SYSTEM ACTIVE — {cat.upper()}",
                "cyclone_id": cid,
                "basin": basin,
                "timestamp": time_str,
                "current_vmax": vmax,
                "reason": f"System sustained winds at {vmax} kt indicate catastrophic destructive wind hazard.",
                "recommendation": "Monitor coastline distance and short-term projected translation trajectory.",
                "badge": "[AI-ASSISTED PROTOTYPE ALERT]"
            })

        # 3. Expansive R35 Footprint Alert
        if r35 >= 140.0:
            alerts.append({
                "alert_id": f"R35-{cid}",
                "type": "LARGE_HAZARD_FOOTPRINT",
                "severity": "MODERATE",
                "title": "EXPANSIVE GALE-FORCE WIND FIELD",
                "cyclone_id": cid,
                "basin": basin,
                "timestamp": time_str,
                "current_vmax": vmax,
                "reason": f"R35 hazard radius extends to {r35} nautical miles ({round(r35 * 1.852)} km).",
                "recommendation": "Prepare marine advisories for outer bands beyond the central convective core.",
                "badge": "[AI-ASSISTED PROTOTYPE ALERT]"
            })

    # Sort alerts by severity (CRITICAL first, then HIGH, then MODERATE)
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MODERATE": 2, "LOW": 3}
    alerts.sort(key=lambda x: severity_order.get(x["severity"], 4))

    return {
        "source": "[AI-ASSISTED PROTOTYPE ALERT ENGINE]",
        "total_active_alerts": len(alerts),
        "disclaimer": "AI-ASSISTED PROTOTYPE ALERT: These notifications are generated by algorithmic detection criteria for demonstration and research purposes. They do not constitute official government meteorological warnings.",
        "alerts": alerts
    }
